name: Build and push Docker image

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Get Docker version from Dockerfile
        run: |
          semver_full=$(head -n1 Dockerfile | grep -oP '([0-9\.]+)')
          semver_major=$(echo "$semver_full" | cut -d '.' -f1)
          semver_minor=$(echo "$semver_full" | cut -d '.' -f2)
          semver_patch=$(echo "$semver_full" | cut -d '.' -f3)
          echo "semver_full=$semver_full"   | tee -a $GITHUB_ENV
          echo "semver_major=$semver_major" | tee -a $GITHUB_ENV
          echo "semver_minor=$semver_minor" | tee -a $GITHUB_ENV
          echo "semver_patch=$semver_patch" | tee -a $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ github.repository }}:${{ github.sha }}

      - name: Get Buildx version from image
        run: |
          docker run ${{ github.repository }}:${{ github.sha }} buildx version | tee buildx_version.txt
          buildx_version=$(cat buildx_version.txt | grep -oP '([0-9]+\.[0-9]+\.[0-9]+)')
          echo "buildx_version=$buildx_version" | tee -a $GITHUB_ENV
          
      - name: Cross-build Docker image and push to Docker Hub
        uses: docker/build-push-action@v5
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.sha }}
            ${{ github.repository }}:${{ env.semver_major }}.${{ env.semver_minor }}
            ${{ github.repository }}:${{ env.semver_major }}.${{ env.semver_minor }}.${{ env.semver_patch }}
            ${{ github.repository }}:${{ env.semver_major }}.${{ env.semver_minor }}.${{ env.semver_patch }}
            ${{ github.repository }}:${{ env.semver_major }}.${{ env.semver_minor }}.${{ env.semver_patch }}-${{ env.buildx_version }}
          labels: |
            org.opencontainers.image.version=${{ env.version }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.ref.name=${{ github.ref }}
          platforms: linux/amd64,linux/arm64

      - name: Tag commit in repository
        uses: actions/github-script@v6
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          TAG_NAME: ${{ env.semver_full }}-${{ env.buildx_version }}
        with:
          script: |
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${process.env.TAG_NAME}`
              })
            } catch (e) {
              // nothing to do here
            }

            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.TAG_NAME}`,
              sha: context.sha
            })
